# File: custom_components/reitti/services.yaml
# Date: 2025-09-13

send_location:
  name: Send Location
  description: Push custom location payload to Reitti
  fields:
    device:
      description: Device tracker entity
      example: device_tracker.phone
    lat:
      description: Latitude
      example: 51.123
    lon:
      description: Longitude
      example: 0.456
